<?php

namespace Admin\Controller;

class EmailController extends __Controller {

    protected $form = array(
        'email' => array(
            'title' => '接收者Email',
            'type' => 'email',
            'name' => 'email'
        ),
        'title' => array(
            'title' => '邮件标题',
            'type' => 'text',
            'name' => 'title'
        ),
        'content' => array(
            'title' => '邮件内容',
            'description' => '邮件发送功能依赖配置文件中的邮箱配置',
            'type' => 'textarea',
            'name' => 'content'
        )
    );

    public function index() {
        $this->meta_title = '已发送邮件列表';
        $this->lists['order'] = array('create_time' => 'desc');
        parent::index();
    }

    public function add()
    {
        parent::add(); // TODO: Change the autogenerated stub
    }

}