<?php

namespace Admin\Controller;

class NewsCategoryController extends __Controller {

    protected $form = array(
        'title' => array(
            'title' => '分类名称',
            'type' => 'text',
            'name' => 'title'
        ),
        'slug' => array(
            'title' => '分类别名',
            'remark' => '分类的唯一标识符，用于调用',
            'type' => 'text',
            'name' => 'slug'
        ),
        'detail' => array(
            'title' => '分类描述',
            'remark' => '250字以内',
            'type' => 'textarea',
            'name' => 'detail'
        )
    );

    public function index() {
        $this->meta_title = '资讯分类';
        parent::index();
    }

    public function add()
    {
        parent::add(); // TODO: Change the autogenerated stub
    }

    public function edit($id)
    {
        parent::edit($id); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function sort($id, $value)
    {
        parent::sort($id, $value); // TODO: Change the autogenerated stub
    }

}